spring:
  application:
    name: high-traffic-result-distribution-system

  datasource:
    url: jdbc:postgresql://localhost:5432/high_traffic_result_distribution_system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3


    consumer:
      group-id: result-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  data:
    redis:
      host: localhost
      port: 6379

rate-limit:
  max-requests: 10
  window-seconds: 60s

app:
  kafka:
    topic:
      result-generation: result-generation-topic






